- hosts: all
  gather_facts: false
  become: true

  vars:
    app_dir: /home/choihw/CashMan-Backend-TS
    branch: main
    image: ghcr.io/hyeongu01/cashman-backend-ts:latest

  tasks:
#    - name: Login to GHCR
#      community.docker.docker_login:
#        registry_url: ghcr.io
#        username: "{{  }}"
#    - name: Pull image
#      community.docker.docker_image:
#        name: "{{ image }}"
#        source: pull
#        force_source: true
    - name: 환경변수 확인
      ansible.builtin.shell: env | grep -i semaphore || true  # grep 실패해도 계속 진행
      register: result
      delegate_to: localhost   # ← Pi가 아닌 Semaphore 서버에서 실행

    - name: 출력
      ansible.builtin.debug:
        msg: "{{ result.stdout }}"
      delegate_to: localhost

    - name: test ping
      ansible.builtin.command: echo "test"
      register: result

    - name: debug print
      ansible.builtin.debug:
        msg: "{{ result.stdout }}"


