on:
  workflow_dispatch:
#    inputs:
#

env:
  re: re

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: "cashman-backend-ts"
          package-type: "container"
          min-versions-to-keep: 15
          ignore-versions: '^latest$'
